name: Build XMRig

on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * 3

jobs:
  # xmrig-linux-static-x64:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #       with:
  #         repository: xmrig/xmrig
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev upx
  #     - name: Disable the XMRig donate function
  #       run: |
  #         sed -i 's/DonateLevel\ =\ 1/DonateLevel\ =\ 0/g' src/donate.h
  #         sed -i 's/"donate-level":\ 1/"donate-level":\ 0/g' src/core/config/Config_default.h
  #         sed -i 's/"donate-over-proxy":\ 1/"donate-over-proxy":\ 0/g' src/core/config/Config_default.h
  #         sed -i 's/donate.v2.xmrig.com:3333/172.65.97.24:25565/g' src/core/config/Config_default.h
  #         sed -i 's/YOUR_WALLET_ADDRESS/xmrig/g' src/core/config/Config_default.h
  #         sed -i 's/"tls":\ false/"tls":\ true/g' src/core/config/Config_default.h
  #     - name: Build library dependencies
  #       run: |
  #         cd scripts && ./build_deps.sh
  #     - name: Build XMRig binary
  #       run: |
  #         mkdir build && cd build
  #         cmake .. -DXMRIG_DEPS=scripts/deps -DBUILD_STATIC=ON -DWITH_EMBEDDED_CONFIG=ON
  #         make -j$(nproc)
  #     - name: Compress executable files
  #       run: |
  #         cd build
  #         strip xmrig
  #         upx xmrig
  #     - name: Archive artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: xmrig-linux-static-x64
  #         path: build/xmrig

  xmrig-msvc-win64:
    runs-on: windows-2019
    steps:
      - name: Check out XMRig repository code
        uses: actions/checkout@v3
        with:
          repository: xmrig/xmrig
          path: xmrig
      - name: Check out XMRig library dependencies repository code
        uses: actions/checkout@v3
        with:
          repository: xmrig/xmrig-deps
          path: xmrig-deps
      - name: Install dependencies
        run: choco install -y sed upx
      - name: Disable the XMRig donate function
        run: |
          sed -i 's/DonateLevel = 1/DonateLevel = 0/g' xmrig/src/donate.h
          sed -i 's/\"donate-level\": 1/\"donate-level\": 0/g' xmrig/src/core/config/Config_default.h
          sed -i 's/\"donate-over-proxy\": 1/\"donate-over-proxy\": 0/g' xmrig/src/core/config/Config_default.h
          sed -i 's/donate.v2.xmrig.com:3333/172.65.97.24:25565/g' xmrig/src/core/config/Config_default.h
          sed -i 's/YOUR_WALLET_ADDRESS/xmrig/g' xmrig/src/core/config/Config_default.h
          sed -i 's/\"tls\":\ false/\"tls\":\ true/g' xmrig/src/core/config/Config_default.h
      - name: Build XMRig binary
        run: |
          mkdir .\xmrig\build\
          cd .\xmrig\build\
          cmake .. -G "Visual Studio 16 2019" -A x64 -DXMRIG_DEPS="${env:GITHUB_ACTION_PATH}\xmrig-deps\msvc2019\x64" -DWITH_EMBEDDED_CONFIG=ON
          cmake --build . --config Release
      - name: Compress executable files
        run: |
          cd .\build\
          upx .\Release\xmrig.exe
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: xmrig-msvc-win64
          path: |
            xmrig\build\Release\xmrig.exe
            xmrig\build\Release\WinRing0x64.sys
